### PR TITLE
Update

### PR DESCRIPTION
**Pull request by huonw**

### CODE REVIEW

**Comment by autohuonw** [comment]
@huonw: no appropriate reviewer found, use r? to override

**Comment by huonw** [comment]
@autohuonw r+

**Comment by autohuonw** [comment]
:pushpin: Commit 739d324 has been approved by `huonw`

**Comment by autohuonw** [comment]
:hourglass: Testing commit 739d324 with merge 65b88b5...

**Comment by huonw** [comment]
@autohuonw r+

**Comment by autohuonw** [comment]
:pushpin: Commit 5ed36a2 has been approved by `huonw`

**Comment by autohuonw** [comment]
:hourglass: Testing commit 5ed36a2 with merge e3247da...

**Comment by huonw** [comment]
@autohuonw retry force

**Comment by huonw** [comment]
@autohuonw retry

**Comment by autohuonw** [comment]
:hourglass: Testing commit 5ed36a2 with merge eaf9272...

**Comment by huonw** [comment]
@autohuonw retry

**Comment by autohuonw** [comment]
:hourglass: Testing commit 5ed36a2 with merge 1b8c3f0...

**Comment by autohuonw** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/huonw/slow_primes/builds/55119634)

**Pull request merged**
