### PR TITLE
Update to (d17d6e7f1 2015-04-02) (built 2015-04-03)

### PR DESCRIPTION
**Pull request by zsiciarz**
Fixed extern crate import and removed deprecated traits. These changes are compatible with the latest nightly but _not_ the 1.0.0 beta (`BitVec` is still unstable, unfortunately).

### CODE REVIEW

**Comment by autohuonw** [comment]
r? @huonw

(rust_highfive has picked a reviewer for you, use r? to override)

**Comment by huonw** [comment]
@autohuonw r+

Awesome, thanks!

**Comment by autohuonw** [comment]
:pushpin: Commit 10f99d3 has been approved by `huonw`

**Comment by autohuonw** [comment]
:hourglass: Testing commit 10f99d3 with merge fe8f56d...

**Comment by autohuonw** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/huonw/slow_primes/builds/57236760)

**Pull request merged**
